### ISSUE TITLE
readers.rxp: No output

### ISSUE THREAD

**Issue by sedot42** [PDAL/PDAL#2226]
Hi, I encountered a problem using readers.rxp compiled with rivlib-2_5_7-x86_64-linux-gcc55. Despite the input file being 1.2 GB, the output .las-file is 227 bytes. I'm using the following pipeline executed via `pdal pipeline pipe.json`
```
{
    "pipeline": [
        {
            "type": "readers.rxp",
            "filename": "180418_110027.rxp",
            "sync_to_pps": "true",
            "reflectance_as_intensity": "true"
        },
        {
            "type": "writers.las",
            "filename": "outputfile.las",
            "discard_high_return_numbers": "true"
        }
    ]
}
```

Since the output file is only 227 bytes, I can post it in its entirety:
```
$ cat outputfile.las
LASFWaPDALPDAL 1.7.2 (Releas)���"{�G�z�?{�G�z�?{�G�z�?���������������������������������������������%
```
I'll be happy to provide any more information.

**Comment by abellgithub** [comment]
What is the output from `pdal info` on the input file?

**Comment by sedot42** [comment]
```
$ stat 180418_110027.rxp
  File: 180418_110027.rxp
  Size: 1244612692	Blocks: 2430888    IO Block: 4096   regular file
Device: 822h/2082d	Inode: 4068        Links: 2
Access: (0777/-rwxrwxrwx)  Uid: ( xxxxxx/  xxxxxx)   Gid: (  100/   users)
$ pdal info 
{
  "filename": "180418_110027.rxp",
  "pdal_version": "1.7.2 (git-version: Release)",
  "stats":
  {
    "statistic":
    [
      {
        "average": 0,
        "count": 0,
        "maximum": -1.797693135e+308,
        "minimum": 1.797693135e+308,
        "name": "X",
        "position": 0,
        "stddev": 0,
        "variance": 0
      },
      {
        "average": 0,
        "count": 0,
        "maximum": -1.797693135e+308,
        "minimum": 1.797693135e+308,
        "name": "Y",
        "position": 1,
        "stddev": 0,
        "variance": 0
      },
      [... exact same result for Z, Intensity, Amplitude, Reflectance, ReturnNumber, NumberOfReturns, GpsTime, IsPpsLocked, Deviation, BackgroundRadiation, EchoRange except for "position" ...]
    ]
  }
}

```

**Comment by hobu** [comment]
I would guess the file is getting opened for initialization and then closed for reading, which is why there are zero points hown. This reader is not widely tested because the SDK is not conveniently available, and it is possible some unrelated reader refactoring has broken it in this way.

**Comment by hobu** [comment]
@gadomski wrote this code, and I think he has access to the SDK if he has some cycles to check.

**Comment by abellgithub** [comment]
There is a test, called rxptest.  Did you build that when you build PDAL and the plugin?  Does it work when you run it?

**Comment by sedot42** [comment]
<details> 
  <summary>I build it again with all unit tests and ran rxptext. </summary>
<pre>
$ ./rxptest
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from RxpReaderTest
[ RUN      ] RxpReaderTest.testConstructor
[       OK ] RxpReaderTest.testConstructor (0 ms)
[ RUN      ] RxpReaderTest.testRead
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:121: Failure
Value of: 177208
Expected: view->size()
Which is: 1191730
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: '\x6' (6)
Expected: expected
Which is: '\x1' (1)
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 2.2699487
Expected: expected
Which is: 2.2641847
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: -0.037321489
Expected: expected
Which is: -0.038409632
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: -1.3291068
Expected: expected
Which is: -1.3245695
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: nan
Expected: expected
Which is: 342656.34
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 2.6945002
Expected: expected
Which is: 2.6872501
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 20.07
Expected: expected
Which is: 19.529999
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 5.8073273
Expected: expected
Which is: 5.3629212
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: false
Expected: expected
Which is: true
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: '\x2' (2)
Expected: expected
Which is: '\x1' (1)
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: '\x6' (6)
Expected: expected
Which is: '\x1' (1)
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 465.0625
Expected: expected
Which is: 2.2685335
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 0.8666712
Expected: expected
Which is: -0.038410265
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: -42.983158
Expected: expected
Which is: -1.3260456
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: nan
Expected: expected
Which is: 342656.34
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 467.11002
Expected: expected
Which is: 2.69175
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 12.349999
Expected: expected
Which is: 19.369999
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: -13.522287
Expected: expected
Which is: 5.2056551
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:63: Failure
Value of: actual
  Actual: 11
Expected: expected
Which is: 5
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: false
Expected: expected
Which is: true
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: '\x3' (3)
Expected: expected
Which is: '\x1' (1)
/home/stefan/Documents/Uni/Heidelberg/Masterarbeit/05_processing/01_preprocessing/pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:73: Failure
Value of: actual
  Actual: '\x6' (6)
Expected: expected
Which is: '\x1' (1)
[  FAILED  ] RxpReaderTest.testRead (432 ms)
[ RUN      ] RxpReaderTest.testNoPpsSync
[       OK ] RxpReaderTest.testNoPpsSync (437 ms)
[ RUN      ] RxpReaderTest.testReflectanceAsIntensity
[       OK ] RxpReaderTest.testReflectanceAsIntensity (435 ms)
[----------] 4 tests from RxpReaderTest (1304 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1304 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RxpReaderTest.testRead

 1 FAILED TEST</pre>
</details>

**Comment by abellgithub** [comment]
I don't see any recent changes of interest in the code.  I think that either the reigl interface has changed or there was something wrong in the driver from the beginning.  If someone wants to get me a copy of the SDK, I can look, otherwise, it will have to wait for someone who has access.

**Comment by hobu** [comment]
```
pdal_compilation/src/PDAL-1.7.2-src/plugins/rxp/test/RxpReaderTest.cpp:121: Failure
Value of: 177208
Expected: view->size()
Which is: 1191730
```

This one is the most interesting. Why is the point count incorrect by such a large amount?

**Comment by abellgithub** [comment]
I've looked at the code.  The interface is very strange.

**Comment by gadomski** [comment]
I can take a look at this tomorrow (I'm on leave today).

> Why is the point count incorrect by such a large amount?

Not sure on this one, but there's an option or two (e.g. `sync_to_pps`) that enables/disables filtering of points based upon various attributes.

**Comment by gadomski** [comment]
@sedot42 I've opened #2228 as a potential fix for your issue. It at least should fix the `rxptest` breakage. If you're able to rebuild with that branch, test, and let us know if it solves anything, that'd be helpful. Alternatively, if you were able to provide the original offending file via some sort of large file sharing service, I could test the PR against your file on my side.

**Comment by abellgithub** [comment]
Closed via #2228

**Comment by sedot42** [comment]
With  #2228 the test runs fine. However, the original problem persists. I managed to reproduce the problem with a smaller file, see the attachment: [rxp_testfile.zip](https://github.com/PDAL/PDAL/files/2489335/rxp_testfile.zip)

**Comment by gadomski** [comment]
Reopening to take a look.

**Comment by abellgithub** [comment]
I can also look as I have acquired a copy of the SDK.  A doc link would be nice, though.  Let me know.

**Comment by gadomski** [comment]
The docs are (usually) contained in the SDK distribution (`docs/` folder). If yours didn't come with it, let me know and I'll email you a copy.

**Comment by gadomski** [comment]
@sedot42 I believe the test file that you provided never syncs to pps; I changed `sync_to_pps` to `false` in your example pipeline and was able to produce an `outputfile.las` with 120278 points, using current master (bd5cd19bb6c2c5530269808958772aaa6f8de607) which incorporates #2228. I'm going to close this issue, but please feel free to re-open if you're still having issues.

**Comment by abellgithub** [comment]
Is there any way we can determine `sync_to_pps` from the data, rather than requiring the user to specify?
