### ISSUE TITLE
[Question] pdal binary path in alpine image

### ISSUE THREAD

**Issue by devon-sofdesk** [PDAL/PDAL#2294]
**Description**
I'm looking for the path of the built `pdal` binary on the [alpine image](https://hub.docker.com/r/pdal/alpine/~/dockerfile/). From what I see in the `Dockerfile` it should be under `/usr`. But I wasn't able to find it.

**Repro steps**
1, `⋊> ~/c/auto-pitch-api on master ⨯ docker pull   pdal/alpine:1.8                                                                                                                                            
1.8: Pulling from pdal/alpine
Digest: sha256:0491cb30bc5f681ac743f815af8b58d25d722663d70416c6a70c2b52397868db
Status: Image is up to date for pdal/alpine:1.8`
2. `⋊> ~/c/auto-pitch-api on master ⨯ docker run --rm -it  pdal/alpine:1.8                                                                                                                                    `
3. `/ # pdal
/bin/sh: pdal: not found`
4. `/ # find /usr/ -name pdal
/ # `

**Notes**
I noticed version 1.8 is being [continuously updated](https://hub.docker.com/r/pdal/alpine/builds/). I'm not sure if that's intentional; I'm my mind if you were to make a new release you would increment the version number.

Thanks

**Comment by abellgithub** [comment]
The 1.8 alpine image was broken but is now fixed.  The pdal application is in /usr/local.

The updates to the 1.8 image you saw weren't changes directly related to the application.  The 1.8 image matches the [release](https://github.com/PDAL/PDAL/releases/tag/1.8.0), with the exception that fixed bugs have been integrated.  We assume that people would rather have an image with known problems fixed than one that exactly matches the state of the code on release.

**Comment by devon-sofdesk** [comment]
@abellgithub Thanks for the update, but I still can't find the application in `/usr/local`.

I pulled the image and searched for it here https://asciinema.org/a/dvEZT96jng7ivzyAbHQeSwNxc .

**Comment by abellgithub** [comment]
It looks like you pulled `latest` but ran `1.8`

To be more clear, pdal is in /usr/local/bin.  Header files and so on are in /usr/local/include.  Libraries are in /usr/local/lib.

I just did this:

```
(pdal) $ docker pull pdal/alpine:1.8
1.8: Pulling from pdal/alpine
4fe2ade4980c: Already exists
e4dd31fe6111: Pull complete
f1fc232a246d: Pull complete
Digest: sha256:05a87972cb60a5dc2b434c783a5dcec5f0ea569bd721f30444e2011ea0504466
Status: Downloaded newer image for pdal/alpine:1.8

(pdal) $ docker run --rm pdal/alpine:1.8 pdal
Usage:
  pdal <options>
  pdal <command> <command options>
  --command        The PDAL command
  --debug          Sets the output level to 3 (option deprecated)
  --verbose, -v    Sets the output level (0-8)
  --drivers        List available drivers
  --help, -h       Display help text
  --list-commands  List available commands
  --version        Show program version
  --options        Show options for specified driver (or 'all')
  --log            Log filename (accepts stderr, stdout, stdlog, devnull as
      special cases)
  --logtiming      Turn on timing for log messages

The following commands are available:
  - delta
  - density
  - diff
  - fauxplugin
  - ground
  - hausdorff
  - info
  - merge
  - pipeline
  - random
  - sort
  - split
  - tile
  - tindex
  - translate

See http://pdal.io/apps/ for more detail
```

**Comment by devon-sofdesk** [comment]
I'm stupid, thanks again.
