### ISSUE TITLE
filesource_id missing as argument in LAS writer

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2862]
The ability to set the `filesource_id` as an option is missing from `writers.las`.

**Comment by hobu** [comment]
We should also add:
* `point_length`
* `dataoffset`

**Comment by abellgithub** [comment]
Fixed with #2863

**Comment by rphillips91** [comment]
Updated my pdal anaconda3 package `pdal pdal 2.0.1 (git-version: Release)` using `conda update pdal`
Error still raised when trying to define `filesource_id` when using `writers.las`.
Do you guys have an eta to this functionality for the anaconda pdal package? Many thanks for pdal

**Comment by hobu** [comment]
@rphillips91 Please create a new conda environment and try to install PDAL into it. This issue was fixed in 2.1.0, which should be available.
