### ISSUE TITLE
C++ API changes for LAS

### ISSUE THREAD

**Issue by tmontaigu** [PDAL/PDAL#3677]
**Describe the problem**

When trying to compile the current PDAL plugin for cloud compare (which is what CC uses to provde support for LAS/LAZ file I/O) or the rewritten version of it agains PDAL master i'm hit with incompatibilities.

Some of them are manageable, however with the new API I don't not know how can I get the VLRs of a LAS file.
They were stored in the header meaning that by saving the `pdal::LasHeader` as metadata attached to the loaded `ccPointCloud` I could save them when writing to a LAS file:
```C++
    for (const pdal::LasVLR &vlr : lasHeader.vlrs()) {
      if (vlr.dataLen() == 0) {
        continue;
      }
      QByteArray dataBase64 = QByteArray(vlr.data()).toBase64();
      if (dataBase64.isEmpty()) {
        ccLog::PrintDebug(
            "Vlr(%s, %d) won't be saved as it has empty data in base64",
            vlr.userId().c_str(), vlr.recordId());
        continue;
      }
      QJsonObject vlrObject;
      vlrObject["description"] = vlr.description().c_str();
      vlrObject["record_id"] = vlr.recordId();
      vlrObject["user_id"] = vlr.userId().c_str();
      vlrObject["data"] = dataBase64.data();

      writerOptions.add("vlrs",
                        QJsonDocument(vlrObject).toJson().toStdString());
    }
  }

```
But now I do not know how I can get the vlrs.

"Compatiblity" layer to handle changes

<details>

```C++
#include <pdal/io/LasHeader.hpp>
#include <pdal/pdal_features.hpp>

#include <CCGeom.h>

#define CC_PDAL_MASTER 1

#if CC_PDAL_MASTER
namespace pdal {
  using LasHeader = pdal::las::Header;
}
#endif

inline bool Has14PointFormat(const pdal::LasHeader &header) {
#if PDAL_VERSION_MINOR <= 2
    return header.has14Format();
#else
  return header.has14PointFormat();
#endif
}

CCVector3d ScalesFromHeader(const pdal::LasHeader &header) {
#if CC_PDAL_MASTER
  return {header.scale.x, header.scale.y, header.scale.z};
#else
  return {header.scaleX(), header.scaledY(), header.scaleZ()};
#endif
}

CCVector3d OffsetsFromHeader(const pdal::LasHeader &header) {
#if CC_PDAL_MASTER
  return {header.offset.x, header.offset.y, header.offset.z};
#else
  return {header.offset(), header.offsetY(), header.offsetZ()};
#endif
}

uint8_t VersionMinorFromHeader(const pdal::LasHeader& header) {
#if CC_PDAL_MASTER
  return header.versionMinor;
#else
  return header.versionMinor();
#endif
}
```

</details>

**Comment by abellgithub** [comment]
The VLR and header access from the LAS reader are oddball holdovers from liblas. I'd be quite happy to remove them altogether.

Are people who are using this feature really using PDAL features, or are they simply wanting to read LAS data? If the latter, lazperf in some ways provides a better interface.

Still, I don't want to break the world. If changing to lazperf is difficult or problematic, I'd be interested in hearing about it.

**Comment by tmontaigu** [comment]
For this plugin we are only interested in reading and writing LAS data and don't use any PDAL feature.

I guess the question is now to select between LASzip and laz-perf as the lib for the next version of the plugin

**Comment by abellgithub** [comment]
I'm going to add back the old API, so no worries -- but do what you prefer with CC.

**Comment by rcoup** [comment]
@abellgithub is this the same issue as https://github.com/connormanning/entwine/pull/275 ?

**Comment by abellgithub** [comment]
@rcoup I believe so.

**Comment by rcoup** [comment]
This is fixed c/- https://github.com/PDAL/PDAL/pull/3682

**Comment by hobu** [comment]
@tmontaigu please reopen this if #3682 doesn't fix your issues. We are getting close to the 2.4 freeze.
