### ISSUE TITLE
LAS reader option to specify the Global Encoding WKT flag

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3803]
example error:
```
(pdal info readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
```

There are datasets that have this incorrectly specified. 

Also a option to specify whether to use WKT or Geotiff tags if both present

**Comment by hobu** [comment]
I fixed this in #3818 by making `readers.las.nosrs` actually work. The error will still come up if you do not specify `readers.las.nosrs=true`, but this update allows the user to over come the error and override the SRS with their own thing.

**Comment by anujdivesh** [comment]
@hobu  Iam using the latest version, still getting the error `PDAL: readers.las: Global encoding WKT flag not set for point format 6 - 10.`
