### ISSUE TITLE
Better error message from writers.gdal with no input

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3834]
writers.gdal reports a range error when there is no input, which is accurate, but also not that helpful. If there is no input, the code should simply report that if possible.

**Comment by isagint** [comment]
Is there a way to work around this? I am currently running a pipeline on many boundaries in an EPT dataset. Every `writers` graciously just ignores writing any input, but `writers.gdal` completely halts execution by throwing an error. I just want this step to silently fail as well.

**Comment by ibell13** [comment]
@isagint Looks like there was an `allow_empty` option that wasn't documented or working properly. #4928 should fix it.

**Comment by isagint** [comment]
@ibell13 Yes, I saw that undocumented option but it was still failing at [line 234](https://github.com/PDAL/PDAL/pull/4928/changes#diff-08fbc8f9bdd11c1e89635b0ea8f51cc288095ce5820a29b5a4433d48dd3c3418L234). But this seems to fix it, great! Thanks!

**Comment by isagint** [comment]
@ibell13 To solve this issue, isn't it easiest to do another check on line 264 if `isEmpty` is set or not? If it's not set, throw an empty input error, like on line 305.
