### ISSUE TITLE
Can't build GRASS and QGIS LTR with PDAL 2.6.1

### ISSUE THREAD

**Issue by imincik** [PDAL/PDAL#4273]
**Describe the bug**

When trying to build GRASS and QGIS with PDAL 2.6.1 in nixpkgs they both fail on trying to find PDAL.

### GRASS
* GRASS error message (see: https://github.com/OSGeo/grass/issues/3220 )
```
checking whether to use PDAL... yes
configure: error: *** Unable to locate suitable (>=1.7.1) PDAL library.
```

* Workaround
```
rm libpdalcpp.so
ln -s libpdalcpp.so.?? libpdalcpp.so
```

### QGIS LTR
* QGIS error message
```
CMake Error at cmake/FindPDAL.cmake:76 (MESSAGE):
  Could not find PDAL
Call Stack (most recent call first):
  CMakeLists.txt:437 (find_package)
```

Both packages build fine with PDAL 2.5.6

**Comment by nilason** [comment]
Will likely be solved by #4267.

**Comment by imincik** [comment]
Unfortunately latest QGIS LTR (3.28.13) still can't find PDAL:

```
       >  CMake Error at cmake/FindPDAL.cmake:76 (MESSAGE):
       >  Could not find PDAL
       >  Call Stack (most recent call first):
       >   CMakeLists.txt:437 (find_package)
```

**Comment by nilason** [comment]
> Unfortunately latest QGIS LTR (3.28.13) still can't find PDAL 2.6.2:
> 
> ```
>        >  CMake Error at cmake/FindPDAL.cmake:76 (MESSAGE):
>        >  Could not find PDAL
>        >  Call Stack (most recent call first):
>        >   CMakeLists.txt:437 (find_package)
> ```
> 
> GRASS build is fixed by PDAL 2.6.2

https://github.com/qgis/QGIS/pull/54940 has not been  backported yet.

**Comment by imincik** [comment]
Thank you @nilason .
