### ISSUE TITLE
Poisson filter: No density information is written

### ISSUE THREAD

**Issue by simplelife2010** [PDAL/PDAL#4489]
I am using the latest pdal docker image to generate a mesh from a laz pointcloud with this pipeline:

```
[
    {
        "type" : "readers.las",
        "filename": "ground.laz"
    },
    {
        "type": "filters.poisson",
        "depth": 9,
        "density": true
    },
    {
        "type":"writers.ply",
        "faces":true,
        "filename":"poisson7.ply"
    }
]
```

The ply file has no density property. This also is the case when I use the writers.text writer. The output contains no density information.

**Expected behavior**
The ply file contains a density property

**System/installation information:**

```
$ pdal --version
pdal 2.7.2 (git-version: aa5ec8)
```

**Comment by abellgithub** [comment]
Thanks for the bug report. Fixed with https://github.com/PDAL/PDAL/tree/issue-4489

**Comment by simplelife2010** [comment]
Wow. Thanks a lot.

**Comment by simplelife2010** [comment]
I just checked the updated docker image and the problem persists. Checked with ply and text writers. No density attribute in the output.

**Comment by hobu** [comment]
docker image is built from the maintenance branch. I have picked this back to the branch at d45aee861f35ed4e4b3313d0a34ad93efbad644d and will hopefully be available there soon.

**Comment by simplelife2010** [comment]
I am testing with the newly created docker image sha256:7f4f98ed2e577b4b3e49d6c301531400e516792903862f2dfb8341c9b3fe4d12

Unfortunately I am still stuck. I still see no density in the output. I also tried to configure the density attribute explicitly to the text writer like this:

```
[
    {
        "type" : "readers.las",
        "filename": "ground.laz"
    },
    {
        "type": "filters.poisson",
        "depth": 4,
        "density": true
    },
    {
        "type":"writers.text",
        "filename":"poisson7.txt",
        "order": "X,Y,Z,Density"
    }
]
```

But I get

```
PDAL: writers.text: Dimension not found with name 'Density'
```

Could be I am misunderstanding something. Any help appreciated.

Bruno

**Comment by abellgithub** [comment]
This seems like a docker issue. If you look at the sha in docker hub it doesn't match what you have. I get the same sha when I pull. :shrug:

**Comment by simplelife2010** [comment]
I am referring to the index digest. I think this should be the correct image.
![image](https://github.com/user-attachments/assets/6f351237-2a4a-46f4-825e-e0cad3d75942)

**Comment by simplelife2010** [comment]
```
(venv) ovx-dev-ipm-user@rendering-ovx-lin-dev-07:/mnt/dbs-omniverse-dev/brunovetter/meshing$ docker images
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
pdal/pdal    latest    68adab296363   20 hours ago   2.05GB
(venv) ovx-dev-ipm-user@rendering-ovx-lin-dev-07:/mnt/dbs-omniverse-dev/brunovetter/meshing$ docker inspect 68adab296363|head -20
[
    {
        "Id": "sha256:68adab29636357a27cdb46a0c0d4f2bd3da89e884cd8a8ea676a3b00b93c7964",
        "RepoTags": [
            "pdal/pdal:latest"
        ],
        "RepoDigests": [
            "pdal/pdal@sha256:7f4f98ed2e577b4b3e49d6c301531400e516792903862f2dfb8341c9b3fe4d12"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-09-04T17:53:45.691122613Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
```

**Comment by hobu** [comment]
What does `pdal --version` report? It should report the git sha of the build.

Please try grabbing the image from ghcr and see if it is still incorrect there. https://github.com/PDAL/PDAL/pkgs/container/pdal

Our docker push stuff is configured at https://github.com/PDAL/PDAL/blob/master/.github/workflows/docker.yml and must be configured correctly

**Comment by simplelife2010** [comment]
```
(base) root@dcdb90b61a4e:/# pdal --version
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.7.2 (git-version: aa5ec8)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

Will try the ghcr container.

**Comment by simplelife2010** [comment]
```
(venv) ovx-dev-ipm-user@rendering-ovx-lin-dev-07:/mnt/dbs-omniverse-dev/brunovetter/meshing$ docker pull ghcr.io/pdal/pdal:sha-d45aee86
sha-d45aee86: Pulling from pdal/pdal
Digest: sha256:7f4f98ed2e577b4b3e49d6c301531400e516792903862f2dfb8341c9b3fe4d12
Status: Downloaded newer image for ghcr.io/pdal/pdal:sha-d45aee86
ghcr.io/pdal/pdal:sha-d45aee86
(venv) ovx-dev-ipm-user@rendering-ovx-lin-dev-07:/mnt/dbs-omniverse-dev/brunovetter/meshing$ docker images
REPOSITORY          TAG            IMAGE ID       CREATED        SIZE
ghcr.io/pdal/pdal   sha-d45aee86   68adab296363   21 hours ago   2.05GB
pdal/pdal           latest         68adab296363   21 hours ago   2.05GB
(venv) ovx-dev-ipm-user@rendering-ovx-lin-dev-07:/mnt/dbs-omniverse-dev/brunovetter/meshing$ docker run -it -v .:/work ghcr.io/pdal/pdal:sha-d45aee86 /bin/bash
(base) root@91ae808bb3da:/# pdal --version
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.7.2 (git-version: aa5ec8)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by simplelife2010** [comment]
With pdal --version I always get the git version aa5ec8 on any docker image I tried so far.

**Comment by simplelife2010** [comment]
I am having the same issue when I build the Dockerfile on my machine. It seems the provided pdal version is the same like the one that is installed by this line:
```
mamba install --yes -c conda-forge pdal --only-deps
```

**Comment by simplelife2010** [comment]
I can confirm though that the fix seem to work when I compile pdal from source by myself.

**Comment by hobu** [comment]
Thanks for digging up what's going on. I'll make a new ticket to deal with the Docker containers, which *should* be building from the `*-maintenance` branches.
